name: Backend Code Quality and Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: temurin
          cache: maven

      - name: Full build, format, style check, and tests
        # clean verify 会依次执行 process-sources（Spotless apply/check）、
        # verify（Checkstyle）以及 test
        run: mvn -B clean verify
